### ISSUE TITLE
Add “invite me” in corobo help

### ISSUE THREAD

**Issue by prnvdixit** [coala/corobo#307]
The “corobo help” command should list “invite me” too with a proper description.

Label: initiatives/gci

**Comment by jayvdb** [comment]
Note the help is found associated with the `invite_cmd` in `labhub.py` , in the `re_cmd_name_help`

**Comment by random-access7** [comment]
Hello, I would really like to work on this. If possible can I be assigned this task?

**Comment by random-access7** [comment]
Also, I was going through the script [labhub.py](https://github.com/coala/corobo/blob/master/plugins/labhub.py) and for the `invite_cmd` method, I see that the regex can match to "invite @userto developers" while `match.group(1)` will return "user" (instead of "userto"). I guess this wouldn't affect the functionality much, but might just be a corner-case error? If possible, could I work on this and [#307](https://github.com/coala/corobo/issues/307)?

**Comment by Makman2** [comment]
Please file a new issue, such discussions shouldn't clutter unrelated issues ;)
