### ISSUE TITLE
coafile/commit section: Enhance rules (like on other coala repos)

### ISSUE THREAD

**Issue by Makman2** [coala/corobo#422]
We are currently missing a max-shortlog-length, imperative mood check and issue reference check.

**Comment by Makman2** [comment]
Seems that actually we have already the checks from the `coala/coala` repo, we could additionally add the issue-reference settings from `coala/coala-bears`.

What actually confused me is that gitmate was not complaining on this PR, where the commit violates the style rules: https://github.com/coala/corobo/pull/404

**Comment by jayvdb** [comment]
gitmate is weird lately.
We need CI to be using coala-ci as a fallback

**Comment by yashasingh** [comment]
@Makman2 I was going through the issue and I realized that [line 30](https://github.com/coala/corobo/blob/b8ad75de17ffb45ee0700ad3c118498fa81c0696/.coafile#L30), comparing with other coafiles [coala-bears](https://github.com/coala/coala-bears/blob/1a7c514aff65d804d86ca4df6ea2b51adc5403cc/.coafile#L38) and [coala](https://github.com/coala/coala/blob/a4b2e94b7832105b93bd9f52ca04235a6ef6b9f8/.coafile#L73) and other coala repos, has `commit` instead of `commits`.

Can updating this resolve the issue? We may also include issue-reference settings from `coala/coala-bears`.

**Comment by Makman2** [comment]
@yashasingh you can file a new issue to change the section name from `commits` to `commit` (which definitely makes sense ;D), this one is a different issue.

@jayvdb I'll file a new issue for the CI-checks :+1:

**Comment by Makman2** [comment]
--> https://github.com/coala/corobo/issues/435
