### ISSUE TITLE
CI: Add coala-ci checks

### ISSUE THREAD

**Issue by Makman2** [coala/corobo#435]
gitmate is behaving weird recently, we need a run of coala itself as a fallback.

**Comment by bhavishyagopesh** [comment]
@Makman2  Is this done with the current PR(https://github.com/coala/corobo/pull/437) ?

**Comment by Makman2** [comment]
No this issue is about adding a call to `coala` in our CI, so we don't rely only on gitmate (as it recently failed to flag issues in code recently).

**Comment by bhavishyagopesh** [comment]
@Makman2  Adding `docker run coala/base coala --ci` to `.travis.yml` would work?

**Comment by Makman2** [comment]
Maybe :)

**Comment by jayvdb** [comment]
@Makman2 , I believe that travis and semaphore are both already running coala checks.

https://github.com/coala/corobo/pull/454#issuecomment-348787642 

.travis.yml and .ci/semaphore.tests.sh omit GitCommitBear with `sed -i.bak '/bears = GitCommitBear/d' .coafile` , and that is due to a bug in coala-bears.

**Comment by Makman2** [comment]
Oh do you have the issue link maybe? In that case let's quickly resolve that issue and close this one ;)

**Comment by jayvdb** [comment]
@Makman2 https://github.com/coala/coala-bears/issues/1037

**Comment by jayvdb** [comment]
Bug is bogus.
